// Состояния пользователя в user flow

export const USER_STATES = {
  START: 'START',
  SELECT_DOSAGE: 'SELECT_DOSAGE',
  SELECT_TIMEZONE: 'SELECT_TIMEZONE',
  SELECT_TIME_SINGLE: 'SELECT_TIME_SINGLE',
  SELECT_TIME_FIRST: 'SELECT_TIME_FIRST',
  SELECT_TIME_SECOND: 'SELECT_TIME_SECOND',
  ENTER_CUSTOM_TIME_SINGLE: 'ENTER_CUSTOM_TIME_SINGLE',
  ENTER_CUSTOM_TIME_FIRST: 'ENTER_CUSTOM_TIME_FIRST',
  ENTER_CUSTOM_TIME_SECOND: 'ENTER_CUSTOM_TIME_SECOND',
  CONFIRM_TIME_SINGLE: 'CONFIRM_TIME_SINGLE',
  CONFIRM_TIME_FIRST: 'CONFIRM_TIME_FIRST',
  CONFIRM_TIME_SECOND: 'CONFIRM_TIME_SECOND',
  REMINDER_SET: 'REMINDER_SET',
  EDITING_REMINDER: 'EDITING_REMINDER',
};
